[application]
name = "kdx"
title = "Karlsen Desktop"
version = "package.json::version"
organization = "Karlsen Network"

[description]
short = "Desktop Node and Wallet for Karlsen"
long = """
Karlsen Desktop is a desktop wallet and a p2p network node instance. This
application allows you to participate in the Karlsen network by running a
local node instance and offers access to a local wallet, compatible with
the web wallet available at https://wallet.karlsencoin.com
"""

[package]
archive = { include = true }
signatures = ["SHA256"]
build = [
    { NPM = { clean = true } }
]
# wasm = "root/wasm"
resources = "resources/setup"
output = "setup/$PLATFORM-$ARCH"
include = [
    { glob = [
            "bin/*",
            "*.js",
            "resources/**.css",
            "resources/images/*.*",
            "resources/**.ttf",
            "resources/**.woff",
            "resources/**.svg",
            "i18n.*",
            "modules/*",
            "lib/*",
            "node_modules/*",
            "package.json"
        ]},
]

[[action]]
items = [{ copy = { glob = [
        ".templates",
        ".defaults",
        "CHANGELOG.md"
    ], to = "$TARGET", hidden = true}}]

[[dependency]]
name = "karlsend"
git = { url = "https://github.com/karlsen-network/karlsend", branch = "master" }
run = [
    { cmd = "go build" },
    { cmd = "go build", cwd = "cmd/genkeypair" },
    { cmd = "go build", cwd = "cmd/karlsenctl" },
    { cmd = "go build", cwd = "cmd/karlsenwallet" },
]
copy = [
    { regex = [
        "karlsend(.exe)?$",
        "genkeypair(.exe)?$",
        "karlsenctl(.exe)?$",
        "karlsenwallet(.exe)?$",
    ], to = "bin/$PLATFORM-$ARCH", flatten = true },
]

[[dependency]]
name = "karlsen-miner"
platform = ["windows", "linux"]
git = { url = "https://github.com/karlsen-network/karlsen-miner", branch = "main" }
run = [{ argv = ["cargo","build","--release","-p","karlsencuda"] }]
copy = [
    { regex = [
        "target/release/karlsencuda(.so|.dll)$",
        "target/release/karlsenopencl(.so|.dll)$",
        "target/release/karlsen-miner(.exe)?$",
    ], to = "bin/$PLATFORM-$ARCH", flatten = true },
    # { file = "target/release/karlsen-miner$EXE", to = "bin/$PLATFORM-$ARCH/gpuminer$EXE" },
]

[nwjs]
version = "0.55.0"
ffmpeg = false

[macos-disk-image]
window_caption_height = 60
window_position = [400,100]
window_size = [485,330]
icon_size = 72
application_icon_position = [100,158]
system_applications_folder_position = [385,158]

[windows]
uuid = "8d51c029-f5dc-44d8-b453-f93629fee7b7"
group = "Karlsen"
# run_on_startup = "everyone"
run_after_setup = true

[images]
application="logo.png"
macos-application="Icon1024.png"
macos-disk-image="kdx-dmg.png"
innosetup-icon="logo.png"
innosetup-wizard-small="kdx-55x58.bmp"
innosetup-wizard-large="kdx-164x314.bmp"

[languages]
languages = ["english","french"]

[firewall]
application = { direction = "in+out" }
rules = [
    { name = "Karlsen Node", program = "bin/windows-x64/karlsend.exe", direction="in+out" },
    { name = "Karlsen GPU Miner", program = "bin/windows-x64/gpuminer.exe", direction="out" }
]
